document.write("<style>");
document.write(".buybtc {");
document.write("    border: 1px solid #c6fbe7;");
document.write("    padding: 5px 10px 5px 10px;");
document.write("    margin: 10px 15px;");
document.write("    line-height: 50px;");
document.write("    border-radius: 3px;");
document.write("    box-shadow: 0 0 17px rgb(224 224 224 \/ 49%);");
document.write("    background: url(https:\/\/0xzx.com\/img\/coinzilla-fav.png) no-repeat #fff;");
document.write("    background-position: top 7px left 3px;");
document.write("}");
document.write(".buybtc:hover {");
document.write("	background: url(https:\/\/0xzx.com\/img\/coinzilla-fav.png) no-repeat #000;");
document.write("    background-position: top 7px left 3px;");
document.write("}");
document.write(".swap {");
document.write("    font-size: 18px;");
document.write("    font-weight: 700;");
document.write("    color: #757884;");
document.write("    padding-left: 25px;");
document.write("}");
document.write(".swapad {");
document.write("    text-shadow: none;");
document.write("    text-align: center;");
document.write("    max-width: 300px;");
document.write("    background: #fff6f6;");
document.write("}");
document.write("");
document.write(".swap:hover {");
document.write("    font-weight: 700;");
document.write("    color:#f75876;");
document.write("    font-style: italic;");
document.write("}");
document.write(".contract {");
document.write("    display: block;");
document.write("    width: 300px;");
document.write("    background: #edfff5;");
document.write("    font-size: 12px;");
document.write("    font-family: cursive;");
document.write("}");
document.write(".social {");
document.write("");
document.write("font-size: 12px;");
document.write(" font-family: cursive;");
document.write("}");
document.write(".contract-title {");
document.write("");
document.write("}");
document.write("a {");
document.write(" text-decoration: none!important;");
document.write("}");
document.write("<\/style>");
document.write("");
document.write("<div class=\"swapad\">");
document.write("<img src=\"https:\/\/0xzx.com\/img\/cake.png\" style=\"height: 50px;float: left;line-height: 50px;\"><a href=\"https:\/\/token.0xzx.com\/#buy-token\" rel=\"nofollow external noopener noreferrer\" target=\"_blank\" ><span class=\"buybtc swap\">SWAP 0XZX TOKEN<\/span><\/a>");
document.write("<div class=\"contract\"><a href=\"https:\/\/bscscan.com\/token\/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b\" rel=\"nofollow external noopener noreferrer\" target=\"_blank\">0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b<\/a><\/div>");
document.write("<span class=\"social\"><a href=\"https:\/\/t.me\/chat0x\" rel=\"nofollow external noopener noreferrer\" target=\"_blank\">TELEGRAM: @chat0x<\/a><\/span> ~ <span class=\"social\"><a href=\"https:\/\/twitter.com\/0xzxcom\" rel=\"nofollow external noopener noreferrer\" target=\"_blank\">TWITTER: @0xzxcom<\/a><\/span>");
document.write("<\/div>");
document.write("");
